In [1]:
import torch
tensor_0d = torch.FloatTensor([1.0])
print(tensor_0d.squeeze())
print(tensor_0d.shape)
print(tensor_0d.dtype)

tensor(1.)
torch.Size([1])
torch.float32


In [2]:
tensor_1d = torch.FloatTensor([1.0, 2.0, 3.0])
print(tensor_1d.squeeze())
print(tensor_1d.shape)
print(tensor_1d.dtype)

tensor([1., 2., 3.])
torch.Size([3])
torch.float32


In [3]:
tensor_2d = torch.FloatTensor([[1.0, 2.0], [3.0, 4.0]])
tensor_2d.squeeze()
print(tensor_2d.shape)
print(tensor_2d.dtype)

torch.Size([2, 2])
torch.float32


In [4]:
tensor_3d = torch.FloatTensor([[[1.0, 2.0], [3.0, 4.0]], [[4.0, 5.0], [6.0, 7.0]]])
print(tensor_3d.squeeze())
print(tensor_3d.shape)
print(tensor_3d.dtype)

tensor([[[1., 2.],
         [3., 4.]],

        [[4., 5.],
         [6., 7.]]])
torch.Size([2, 2, 2])
torch.float32


In [5]:
tensor_4d = torch.FloatTensor([[[[1.0, 2.0], [3.0, 4.0]], [[4.0, 5.0], [6.0, 7.0]]], [[[8.0, 9.0], [10.0, 11.0]], [[12.0, 13.0], [14.0, 15.0]]]])
print(tensor_4d.squeeze())
print(tensor_4d.shape)
print(tensor_4d.dtype)

tensor([[[[ 1.,  2.],
          [ 3.,  4.]],

         [[ 4.,  5.],
          [ 6.,  7.]]],


        [[[ 8.,  9.],
          [10., 11.]],

         [[12., 13.],
          [14., 15.]]]])
torch.Size([2, 2, 2, 2])
torch.float32


In [6]:
tensor_0d_int = tensor_0d.to(torch.int)
tensor_0d_int

tensor([1], dtype=torch.int32)

In [7]:
tensor_1d_int = tensor_1d.to(torch.int)
tensor_1d_int

tensor([1, 2, 3], dtype=torch.int32)

In [8]:
tensor_2d_int = tensor_2d.to(torch.int)
tensor_2d_int

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [9]:
tensor_3d_int = tensor_3d.to(torch.int)
tensor_3d_int

tensor([[[1, 2],
         [3, 4]],

        [[4, 5],
         [6, 7]]], dtype=torch.int32)

In [10]:
tensor_4d_int = tensor_4d.to(torch.int)
tensor_4d_int

tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]], dtype=torch.int32)